### ISSUE TITLE
More Maintainers!

### ISSUE THREAD

**Issue by evantahler** [taskrabbit/forklift#43]
@rgarver and @rahilsondhi: I'm betting you folks use this tool far more than I do... want to be maintainers?

**Comment by rahilsondhi** [comment]
Sorry @evantahler I'm not using this tool anymore

**Comment by evantahler** [comment]
Ah! Congrats on the new job @rahilsondhi

**Comment by rgarver** [comment]
I'm game to pick it up. We are still using this quite a bit.
